import { applyPhonotactics, addInitialSecondary } from "../src/en/phonotactics";
import EnG2P from "../src/en/g2p";

// Audit regressions for src/en/phonotactics.ts.
//
// applyPhonotactics runs on the output of BOTH the rule path and the
// dictionary/exception-table path, so every rule in it must be measured
// against the lexicon it post-processes, not just against the rule path.
// These cases pin the environments where a rule was found to be rewriting
// pronunciations the lexicon already had right. Each frame carries the
// dict ratio that decided it; the words named are class exemplars.
//
// The unit tests below call applyPhonotactics directly: the mined exception
// table is regenerated by build-dict, so a full-IPA expectation routed
// through EnglishG2P can move underneath the test, but the phonotactic
// transform on a given input string cannot.

describe("phonotactics: STRUT promotion is a transcription-convention choice", () => {
  // normalizeStrut promotes a stressed /ə/ to /ʌ/ and demotes an unstressed
  // /ʌ/ to /ə/. The two references this repo scores against disagree about
  // that position, so the promotion is an adapter, not a phonological claim:
  //
  //   data/en/dict.json (open-dict-data ipa-dict en_US, which the shipped
  //     exception table copies verbatim) writes /ə/ under stress too — it
  //     contains /ʌ/ 0 times against 5714 entries with a stressed /ə/.
  //   scripts/evaluate-common-accuracy.ts (pinned CMUdict) maps AH1/AH2 to
  //     /ʌ/ and AH0 to /ə/, i.e. it wants the promotion.
  //
  // Deleting the promotion measured runtime strict parity 92.28% → 95.10%
  // and top-5000 segment accuracy 92.26% → 89.62%; 136 of the 346 remaining
  // top-5000 mismatches would then differ from CMUdict by ə/ʌ alone. These
  // tests pin the convention as it currently ships so the choice is explicit.
  it("promotes a stressed schwa to STRUT", () => {
    expect(applyPhonotactics("ˈhəndɝd", "hundred")).toBe("ˈhʌndɝd");
    expect(applyPhonotactics("ˈwən", "one")).toBe("ˈwʌn");
  });

  it("demotes an unstressed STRUT to schwa", () => {
    expect(applyPhonotactics("ˈtɹʌbəɫsʌm", "troublesome")).toBe("ˈtɹʌbəɫsəm");
  });

  it("exempts the weak-form function word 'the'", () => {
    expect(applyPhonotactics("ˈðə", "the")).toBe("ˈðə");
  });
});

describe("phonotactics: /ɪɹ/ coalescence skips a diphthong offglide", () => {
  // /[aeoɔ]ɪɹ/ 342 : /[aeoɔ]ɝ/ 10 — the /ɪ/ after a diphthong nucleus is an
  // offglide, so /aɪɹ/ is /aɪ/ + onset /ɹ/, not a lax /ɪ/ before coda /ɹ/.
  it("keeps aɪɹ / eɪɹ / ɔɪɹ intact", () => {
    expect(applyPhonotactics("ˈbaɪɹən", "byron")).toBe("ˈbaɪɹən");
    expect(applyPhonotactics("ˈsaɪɹəs", "cyrus")).toBe("ˈsaɪɹəs");
    expect(applyPhonotactics("ˈkɔɪɹoʊ", "coiro")).toBe("ˈkɔɪɹoʊ");
    expect(applyPhonotactics("ˌkaɪɹoʊˈpɹæktɪk", "chiropractic")).toBe(
      "ˌkaɪɹoʊˈpɹæktɪk",
    );
  });

  it("still coalesces an unstressed /ɪɹ/ after a consonant", () => {
    // /Cɝ/ 20066 : /CɪɹV/ 932.
    expect(applyPhonotactics("ˈsɛntɪɹd", "centered")).toBe("ˈsɛntɝd");
    expect(applyPhonotactics("ˈbætɪɹiz", "batteries")).toBe("ˈbætɝiz");
  });
});

describe("phonotactics: syllabic-/l/ epenthesis needs an obstruent onset", () => {
  // After an obstruent the lexicon epenthesizes without exception
  // (/Cəɫ/+C 778 : /Cɫ/+C 0); after /ɹ/ it does not (carlson, marlboro),
  // and /ɫj/, /ɫw/ are onsets (306 : 16).
  it("does not break up a /ɹl/ coda", () => {
    expect(applyPhonotactics("ˈkɑɹɫsən", "carlson")).toBe("ˈkɑɹɫsən");
    expect(applyPhonotactics("ˈmɑɹɫbɝoʊ", "marlboro")).toBe("ˈmɑɹɫbɝoʊ");
  });

  it("does not break up an /lj/ or /lw/ onset", () => {
    expect(applyPhonotactics("ˌɪnˈtæɡɫjoʊ", "intaglio")).toBe("ˌɪnˈtæɡɫjoʊ");
    expect(applyPhonotactics("ˈbɫwin", "blouin")).toBe("ˈbɫwin");
  });

  it("still epenthesizes after an obstruent", () => {
    expect(applyPhonotactics("ˈsaɪkɫd", "cycled")).toBe("ˈsaɪkəɫd");
  });
});

describe("phonotactics: word-initial /h/ + sonorant is a licit onset", () => {
  // The lexicon keeps it 24 times and drops it once (hlavaty, hruska,
  // hmong, hnat). Word-final /h/ is still dropped: 2754 : 18.
  it("keeps hl / hr / hm / hn word-initially", () => {
    expect(applyPhonotactics("ˈhɫæd", "hlad")).toBe("ˈhɫæd");
    expect(applyPhonotactics("ˈhɹubi", "hruby")).toBe("ˈhɹubi");
    expect(applyPhonotactics("ˈhmɔŋ", "hmong")).toBe("ˈhmɔŋ");
    expect(applyPhonotactics("ˈhnæt", "hnat")).toBe("ˈhnæt");
  });

  it("still drops a word-internal or word-final /h/", () => {
    expect(applyPhonotactics("ˈæhktɝ", "akhtar")).toBe("ˈæktɝ");
    expect(applyPhonotactics("ˈbɔɹəh", "borah")).toBe("ˈbɔɹə");
  });
});

describe("phonotactics: -ed allomorph keeps a nucleus schwa", () => {
  // An obstruent + /ɹ/ + /d/ is not a possible English coda: /Cɹəd/ 9,
  // /Cɹd/ 0.
  it("does not create an illegal /Cɹd/ coda", () => {
    expect(applyPhonotactics("ˈæɫfɹəd", "alfred")).toBe("ˈæɫfɹəd");
    expect(applyPhonotactics("ˈheɪtɹəd", "hatred")).toBe("ˈheɪtɹəd");
    expect(applyPhonotactics("ˈseɪkɹəd", "sacred")).toBe("ˈseɪkɹəd");
  });

  it("still applies the allomorph elsewhere", () => {
    expect(applyPhonotactics("ˈhaɪpəd", "hyped")).toBe("ˈhaɪpt");
    expect(applyPhonotactics("ˈɹaɪməd", "rhymed")).toBe("ˈɹaɪmd");
  });
});

describe("phonotactics: initial secondary stress is rule-path only", () => {
  // addInitialSecondary is no longer part of applyPhonotactics — applied to
  // lexical output it stamped a ˌ the lexicon does not write on 1550
  // exception-table entries. applyPostStress calls it for the rule and
  // morphology paths instead.
  it("is not applied by applyPhonotactics", () => {
    expect(applyPhonotactics("ɛnsaɪkɫəˈpidiə", "encyclopedia")).toBe(
      "ɛnsaɪkɫəˈpidiə",
    );
  });

  it("still marks an unmarked long Latinate word when called directly", () => {
    expect(addInitialSecondary("ɛnsaɪkɫəˈpidiə")).toBe("ˌɛnsaɪkɫəˈpidiə");
  });
});

describe("phonotactics: lexical entries survive the pass intact", () => {
  // The regression this audit exists for: a phonotactics rule that rewrites
  // a correct lexical pronunciation ships a worse one than the table holds.
  const g2p = new EnG2P();
  const cases: Array<[string, string]> = [
    ["byron", "ˈbaɪɹən"],
    ["admire", "ædˈmaɪɹ"],
    ["carlson", "ˈkɑɹɫsən"],
    ["hruska", "ˈhɹʊskə"],
    ["alfred", "ˈæɫfɹəd"],
    ["chiropractic", "ˌkaɪɹoʊˈpɹæktɪk"],
  ];
  it.each(cases)("%s", (word, ipa) => {
    expect(g2p.predict(word, "en")).toBe(ipa);
  });
});
